version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_DATABASE=phishing_db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  phishing-detector:
    image: ntshuxeko/phishing-detector:latest
    container_name: phishing-detector
    depends_on: 
      - mysql
    ports:
      - 8080:8080

  front-end:
    image: ntshuxeko/front-end:latest
    container_name: front-end
    ports:
      - 4200:80
    links:
      - phishing-detector
        
volumes:
  db:
