version: '3'
services:

  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      - MYSQL_DATABASE=phishing_db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  phishing-detector:
    image: ntshuxeko/phishing-detector:latest
    container_name: phishing-detector
    restart: always
    ports:
      - '8080:8080'
    links:
      - mysql

  front-end:
    image: ./front-end
    container_name: front-end
    ports:
      - 4200:80
    links:
      - phishing-detector


volumes:
  db: