version: '3'
services:

  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      - MYSQL_DATABASE=backend_db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  phishing-detector:
    build: ./phishing-detector
    container_name: phishing-detector
    environment:
      - DB_SERVER=mysql
      - MYSQL_DATABASE=backend-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    ports:
      - 8080:8080
    links:
      - mysql

  front-end:
    build: ./front-end
    container_name: front-end
    ports:
      - 4200:80
    links:
      - phishing-detector


volumes:
  database-data: