version: '3'
services:

  postgres:
    image: "postgres:9.6-alpine"
    container_name: postgres
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=backend-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  phishing-detector:
    build: ./phishing-detector
    container_name: phishing-detector
    environment:
      - DB_SERVER=postgres
      - POSTGRES_DB=backend-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 8080:8080
    links:
      - postgres

  front-end:
    build: ./front-end
    container_name: front-end
    ports:
      - 4200:80
    links:
      - phishing-detector


volumes:
  database-data: