phishing:
    app:
        jwtExpirationMs: 1800000
        jwtSecret: SPHISHING928089FA5F1B21AB01B65D37B71DD6F54526EE33A8AA7CC5B72A7B766F073D9CWEBAPP
server:
    cors: true
spring:
    datasource:
        url: jdbc:mysql://13.59.127.196:3306/phishing_db
        username: root
        password: Venus@18
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    flyway:
        url: jdbc:mysql://13.59.127.196:3306/phishing_db
        user: "root"
        password: "Venus@18"
        schemas: phishing_db
        enabled: false
