name: Build and Deploy Backend

env:
  AWS_USER: ubuntu
  EC2_INSTANCE: ec2-13-244-123-141.af-south-1.compute.amazonaws.com
  APPLICATION_PATH: /home/ubuntu/application
  APP_NAME: phishing-detector
  DOCKER_REPOSITORY: ntshuxeko
  DOCKER_USERNAME: ntshuxeko
  
on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ env.APP_NAME }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Maven clean package
      run: mvn clean package
    
    - name: Docker build and Tag
      run: docker build -t ${{ env.DOCKER_REPOSITORY }}/${{ env.APP_NAME }}:latest .
    
    - name: Docker login
      run: docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

    - name: Docker push
      run: docker push ${{ env.DOCKER_REPOSITORY }}/${{ env.APP_NAME }}:latest
    

